version: '3.3'

services:
    traefik:
      image: traefik:alpine
      ports:
        - 80:80
        - 443:443
        - 8080:8080
      volumes:
        - $PWD/traefik/config:/etc/traefik
        - /var/run/docker.sock:/var/run/docker.sock
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:$WORDPRESS_DOMAIN; PathPrefixStrip:/traefik"
        - "traefik.port=8080"

    db:
      image: mysql:5.7
      volumes:
        - db-data:/var/lib/mysql
      restart: always
      environment:
        - MYSQL_USER=$MYSQL_USER
        - MYSQL_PASSWORD=$MYSQL_PASS
        - MYSQL_DATABASE=$MYSQL_DBNAME
        - MYSQL_ROOT_PASSWORD=$MYSQL_PASS

    wordpress:
      depends_on:
        - db
      image: wordpress:latest
      links:
        - db:mysql
      ports:
        - 8000:80
      restart: always
      environment:
        - WORDPRESS_DB_HOST=$DB_HOST
        - WORDPRESS_DB_NAME=$DB_NAME
        - WORDPRESS_TABLE_PREFIX=$DB_PREFIX
        - WORDPRESS_DB_USER=$DB_USER
        - WORDPRESS_DB_PASSWORD=$DB_PASSWORD
      volumes:
        - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        - ./wp-app:/var/www/html # Full wordpress project
      labels:
        - traefik.enable=true
        - "traefik.frontend.rule=Host:$WORDPRESS_DOMAIN"

    phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      links:
        - db:mysql
      ports:
        - 8181:80
      environment:
        - MYSQL_USERNAME=$MYSQL_USER
        - MYSQL_ROOT_PASSWORD=$MYSQL_PASS
        - PMA_HOST=db
        - PMA_ABSOLUTE_URI=/phpmyadmin/
        # - PMA_ARBITRARY=1
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:$WORDPRESS_DOMAIN;PathPrefixStrip:/phpmyadmin/"

    poste:
      image: analogic/poste.io
      restart: always
      network_mode: "host"
      expose:
        - 25
        - 80
        - 43
        - 110
        - 143
        - 465
        - 587
        - 993
        - 995
      ports:
        - 8282:80
        - 5353:43
      volumes:
      - mail-data:/data
      environment:
      - HTTPS=ON    
      labels:
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:$WORDPRESS_DOMAIN;PathPrefix:/mail"
        
    jenkins:
      image: jenkins/jenkins
      expose:
        - 8080
        - 50000
      volumes:
        - jenkins_home:/var/jenkins_home
      environment:
        - JENKINS_OPTS=--prefix=/jenkins
      labels:
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:$WORDPRESS_DOMAIN;PathPrefix:/jenkins"
volumes:
    db-data:
    jenkins_home:
    mail-data: