version: '3.3'

services:
    traefik:
      image: traefik:latest
      ports:
        - 80:80
        - 443:443
        - 8080:8080
      volumes:
        - $PWD/traefik/config:/etc/traefik
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - backend
        - frontend
      labels:
        - "traefik.docker.network=frontend"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:$WORDPRESS_DOMAIN; PathPrefixStrip:/traefik"
        - "traefik.port=8080"

    db:
      image: mysql:5.7
      networks:
        - backend
      volumes:
        - db_data:/var/lib/mysql
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=$MYSQL_PASS
        - MYSQL_DATABASE=$MYSQL_DBNAME
        - MYSQL_USER=$MYSQL_USER
        - MYSQL_PASSWORD=$MYSQL_PASS
      labels:
        - "traefik.docker.network=frontend"
        - "traefik.enable=true"

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      networks:
        - backend
        - frontend
 
      environment: 
        - PMA_HOST=db
        - PMA_ABSOLUTE_URI=/phpmyadmin/
        - MYSQL_ROOT_PASSWORD=$MYSQL_PASS     
        # - PMA_ARBITRARY=1
      depends_on:
        - db
      labels:
        - "traefik.docker.network=frontend"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:$WORDPRESS_DOMAIN;PathPrefixStrip:/phpmyadmin/"
        - "traefik.port=80"

    jenkins:
      image: jenkins/jenkins:2.150.2-alpine
      expose:
        - 8080
        - 50000
      # tag::jenkins-env-opts[]
      environment:
        - JENKINS_OPTS=--prefix=/jenkins
      # end::jenkins-env-opts[]
      labels:
        - "traefik.docker.network=frontend"
        - "traefik.enable=true"
        - "traefik.port=8080"
        # end::jenkins-labels-port[]
        # tag::jenkins-labels-rule[]
        - "traefik.frontend.rule=Host:$WORDPRESS_DOMAIN;PathPrefix:/jenkins"
        # end::jenkins-labels-rule[]

    wordpress:
      depends_on:
        - db
      image: wordpress:latest
      networks:
        - backend
        - frontend
      ports:
        - 8000:80
      restart: always
      environment:
        - WORDPRESS_DB_HOST=$DB_HOST
        - WORDPRESS_DB_NAME=$DB_NAME
        - WORDPRESS_TABLE_PREFIX=$DB_PREFIX
        - WORDPRESS_DB_USER=$DB_USER
        - WORDPRESS_DB_PASSWORD=$DB_PASSWORD
      volumes:
        - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        - ./wp-app:/var/www/html # Full wordpress project
      labels:
        - "traefik.docker.network=frontend"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:$WORDPRESS_DOMAIN"
        
volumes:
  db_data: {}
networks:
  frontend:
  backend: